export const HTML_NAMESPACE = 'http://www.w3.org/1999/xhtml';
export const SVG_NAMESPACE = 'http://www.w3.org/2000/svg';
export const MATHML_NAMESPACE = 'http://www.w3.org/1998/Math/MathML';

export const ELEMENT_NAMESPACE_GUESS: Record<string, string | undefined> = {
    // SVG Elements per https://developer.mozilla.org/en-US/docs/Web/SVG/Element
    //'a': SVG_NAMESPACE,
    animate: SVG_NAMESPACE,
    animateMotion: SVG_NAMESPACE,
    animateTransform: SVG_NAMESPACE,
    circle: SVG_NAMESPACE,
    clipPath: SVG_NAMESPACE,
    defs: SVG_NAMESPACE,
    desc: SVG_NAMESPACE,
    discard: SVG_NAMESPACE,
    ellipse: SVG_NAMESPACE,
    feBlend: SVG_NAMESPACE,
    feColorMatrix: SVG_NAMESPACE,
    feComponentTransfer: SVG_NAMESPACE,
    feComposite: SVG_NAMESPACE,
    feConvolveMatrix: SVG_NAMESPACE,
    feDiffuseLighting: SVG_NAMESPACE,
    feDisplacementMap: SVG_NAMESPACE,
    feDistantLight: SVG_NAMESPACE,
    feDropShadow: SVG_NAMESPACE,
    feFlood: SVG_NAMESPACE,
    feFuncA: SVG_NAMESPACE,
    feFuncB: SVG_NAMESPACE,
    feFuncG: SVG_NAMESPACE,
    feFuncR: SVG_NAMESPACE,
    feGaussianBlur: SVG_NAMESPACE,
    feImage: SVG_NAMESPACE,
    feMerge: SVG_NAMESPACE,
    feMergeNode: SVG_NAMESPACE,
    feMorphology: SVG_NAMESPACE,
    feOffset: SVG_NAMESPACE,
    fePointLight: SVG_NAMESPACE,
    feSpecularLighting: SVG_NAMESPACE,
    feSpotLight: SVG_NAMESPACE,
    feTile: SVG_NAMESPACE,
    feTurbulence: SVG_NAMESPACE,
    filter: SVG_NAMESPACE,
    foreignObject: SVG_NAMESPACE,
    g: SVG_NAMESPACE,
    hatch: SVG_NAMESPACE,
    hatchpath: SVG_NAMESPACE,
    image: SVG_NAMESPACE,
    line: SVG_NAMESPACE,
    linearGradient: SVG_NAMESPACE,
    marker: SVG_NAMESPACE,
    mask: SVG_NAMESPACE,
    metadata: SVG_NAMESPACE,
    mpath: SVG_NAMESPACE,
    path: SVG_NAMESPACE,
    pattern: SVG_NAMESPACE,
    polygon: SVG_NAMESPACE,
    polyline: SVG_NAMESPACE,
    radialGradient: SVG_NAMESPACE,
    rect: SVG_NAMESPACE,
    //'script': SVG_NAMESPACE,
    set: SVG_NAMESPACE,
    stop: SVG_NAMESPACE,
    //'style': SVG_NAMESPACE,
    svg: SVG_NAMESPACE,
    switch: SVG_NAMESPACE,
    symbol: SVG_NAMESPACE,
    text: SVG_NAMESPACE,
    textPath: SVG_NAMESPACE,
    //'title': SVG_NAMESPACE,
    tspan: SVG_NAMESPACE,
    use: SVG_NAMESPACE,
    view: SVG_NAMESPACE,

    // MATHML Elements per https://developer.mozilla.org/en-US/docs/Web/MathML/Element
    math: MATHML_NAMESPACE,
    maction: MATHML_NAMESPACE,
    annotation: MATHML_NAMESPACE,
    'annotation-xml': MATHML_NAMESPACE,
    menclose: MATHML_NAMESPACE,
    merror: MATHML_NAMESPACE,
    mfenced: MATHML_NAMESPACE,
    mfrac: MATHML_NAMESPACE,
    mi: MATHML_NAMESPACE,
    mmultiscripts: MATHML_NAMESPACE,
    mn: MATHML_NAMESPACE,
    none: MATHML_NAMESPACE,
    mo: MATHML_NAMESPACE,
    mover: MATHML_NAMESPACE,
    mpadded: MATHML_NAMESPACE,
    mphantom: MATHML_NAMESPACE,
    mprescripts: MATHML_NAMESPACE,
    mroot: MATHML_NAMESPACE,
    mrow: MATHML_NAMESPACE,
    ms: MATHML_NAMESPACE,
    semantics: MATHML_NAMESPACE,
    mspace: MATHML_NAMESPACE,
    msqrt: MATHML_NAMESPACE,
    mstyle: MATHML_NAMESPACE,
    msub: MATHML_NAMESPACE,
    msup: MATHML_NAMESPACE,
    msubsup: MATHML_NAMESPACE,
    mtable: MATHML_NAMESPACE,
    mtd: MATHML_NAMESPACE,
    mtext: MATHML_NAMESPACE,
    mtr: MATHML_NAMESPACE,
    munder: MATHML_NAMESPACE,
    munderover: MATHML_NAMESPACE,
};

export const elementNamespaceTransitionMap: Record<
    string,
    Record<string, { node: string; children: string } | undefined> | undefined
> = {
    [HTML_NAMESPACE]: {
        svg: {
            node: SVG_NAMESPACE,
            children: SVG_NAMESPACE,
        },
        math: {
            node: MATHML_NAMESPACE,
            children: MATHML_NAMESPACE,
        },
    },
    [SVG_NAMESPACE]: {
        foreignObject: {
            node: SVG_NAMESPACE,
            children: HTML_NAMESPACE,
        },
    },
} as const;
