#!/usr/bin/env bash
set -e
cd "$(dirname "$0")/.."
# shellcheck disable=SC1091
source "s/_tools.sh"

echo_info "Checking requirements..."
s/check_requirements
echo_info "Installing dependencies..."
yarn
echo_info "Building..."
node_modules/.bin/tsc -p ./tsconfig.json

if [ "$1" != "--no-done" ]; then
    echo_good "All done"
fi
