#!/usr/bin/env bash
set -e
cd "$(dirname "$0")/.."
# shellcheck disable=SC1091
source "s/_tools.sh"

echo_info "Checking requirements..."
s/check_requirements
echo_info "Installing dependencies..."
yarn
echo_info "Bundling..."
node_modules/.bin/esbuild src/todo.tsx --sourcemap --bundle --outfile=bundle.js

if [ "$1" != "--no-done" ]; then
    echo_good "All done"
fi
