#!/usr/bin/env bash
set -e
cd "$(dirname "$0")/.."
# shellcheck disable=SC1091
source "s/_tools.sh"

if ! command -v node > /dev/null; then
    echo_error "nodejs is required. Please install via https://nodejs.org/"
    exit 1
fi

NODE_VERSION=$(node --version)
RECOMMEND_NODE_VERSION=$(cat .nvmrc)

if [ "$NODE_VERSION" != "$RECOMMEND_NODE_VERSION" ]; then
    echo_warn "WARNING: the current node version does not match the recommended node version."
    echo -n "Current node version: "
    echo_info "$NODE_VERSION"
    echo -n "Recommended node version: "
    echo_info "$RECOMMEND_NODE_VERSION"
    echo_warn "To fix, please install nvm via https://github.com/nvm-sh/nvm and run: nvm use"
    sleep 3
fi

if ! command -v jo > /dev/null; then
    echo_error "jo is required. Please install, via https://github.com/jpmens/jo"
    exit 1
fi
