#!/usr/bin/env bash
set -e
cd "$(dirname "$0")/.."
# shellcheck disable=SC1091
source "s/_tools.sh"

VERSION=$(jq .version package.json)

echo_warn "Cleaning..."
s/clean

echo_info "Building via tsc..."
node_modules/.bin/tsc -p .

echo_info "Bundling esm..."
node_modules/.bin/esbuild build/tsc/src/index.js --define:DEBUG=false --define:VERSION="${VERSION}" --sourcemap --bundle --target=es2020 --format=esm --outdir=build/esm
echo_info "Bundling cjs..."
node_modules/.bin/esbuild build/tsc/src/index.js --define:DEBUG=false --define:VERSION="${VERSION}" --sourcemap --bundle --target=es2020 --format=cjs --outfile=build/cjs/index.js
echo_info "Bundling iife..."
node_modules/.bin/esbuild build/tsc/src/index.js --define:DEBUG=false --define:VERSION="${VERSION}" --sourcemap --bundle --target=es2020 --format=iife --global-name=Revise --outfile=build/browser/index.js
echo_info "Bundling minified iife..."
node_modules/.bin/esbuild build/tsc/src/index.js --define:DEBUG=false --define:VERSION="${VERSION}" --sourcemap --bundle --target=es2020 --format=iife --global-name=Revise --minify --outfile=build/browser/index.min.js

echo_warn "Running tests + performance tests to confirm..."
s/test --perf

if [ "$1" != "--no-done" ]; then
    echo_good "All done"
fi
