#!/usr/bin/env bash
set -e
cd "$(dirname "$0")/.."
# shellcheck disable=SC1091
source "s/_tools.sh"

echo_info "Cleaning..."
s/clean

# TODO: actually have a test runner that can run multiple test files
node_modules/.bin/tsc --noEmit -p .
node_modules/.bin/esbuild src/view.test.tsx --sourcemap --bundle --outfile=test/test-bundle.js
