#!/usr/bin/env bash
set -e
cd "$(dirname "$0")/.."
# shellcheck disable=SC1091
source "s/_tools.sh"

echo_info "Checking requirements..."
s/check_requirements

echo_info "Installing dependencies..."
npm install

echo_info "Typechecking..."
node_modules/.bin/tsc "$@"  -p . --noEmit --emitDeclarationOnly false
