export const HTML_NAMESPACE = 'http://www.w3.org/1999/xhtml';
export const SVG_NAMESPACE = 'http://www.w3.org/2000/svg';
export const MATHML_NAMESPACE = 'http://www.w3.org/1998/Math/MathML';

export const ELEMENT_NAMESPACE_GUESS: Record<string, string | undefined> = {
    // HTML elements per https://html.spec.whatwg.org/multipage/indices.html#elements-3
    a: HTML_NAMESPACE,
    abbr: HTML_NAMESPACE,
    address: HTML_NAMESPACE,
    area: HTML_NAMESPACE,
    article: HTML_NAMESPACE,
    aside: HTML_NAMESPACE,
    audio: HTML_NAMESPACE,
    b: HTML_NAMESPACE,
    base: HTML_NAMESPACE,
    bdi: HTML_NAMESPACE,
    bdo: HTML_NAMESPACE,
    blockquote: HTML_NAMESPACE,
    body: HTML_NAMESPACE,
    br: HTML_NAMESPACE,
    button: HTML_NAMESPACE,
    canvas: HTML_NAMESPACE,
    caption: HTML_NAMESPACE,
    cite: HTML_NAMESPACE,
    code: HTML_NAMESPACE,
    col: HTML_NAMESPACE,
    colgroup: HTML_NAMESPACE,
    data: HTML_NAMESPACE,
    datalist: HTML_NAMESPACE,
    dd: HTML_NAMESPACE,
    del: HTML_NAMESPACE,
    details: HTML_NAMESPACE,
    dfn: HTML_NAMESPACE,
    dialog: HTML_NAMESPACE,
    div: HTML_NAMESPACE,
    dl: HTML_NAMESPACE,
    dt: HTML_NAMESPACE,
    em: HTML_NAMESPACE,
    embed: HTML_NAMESPACE,
    fieldset: HTML_NAMESPACE,
    figcaption: HTML_NAMESPACE,
    figure: HTML_NAMESPACE,
    footer: HTML_NAMESPACE,
    form: HTML_NAMESPACE,
    h1: HTML_NAMESPACE,
    h2: HTML_NAMESPACE,
    h3: HTML_NAMESPACE,
    h4: HTML_NAMESPACE,
    h5: HTML_NAMESPACE,
    h6: HTML_NAMESPACE,
    head: HTML_NAMESPACE,
    header: HTML_NAMESPACE,
    hgroup: HTML_NAMESPACE,
    hr: HTML_NAMESPACE,
    html: HTML_NAMESPACE,
    i: HTML_NAMESPACE,
    iframe: HTML_NAMESPACE,
    img: HTML_NAMESPACE,
    input: HTML_NAMESPACE,
    ins: HTML_NAMESPACE,
    kbd: HTML_NAMESPACE,
    label: HTML_NAMESPACE,
    legend: HTML_NAMESPACE,
    li: HTML_NAMESPACE,
    link: HTML_NAMESPACE,
    main: HTML_NAMESPACE,
    map: HTML_NAMESPACE,
    mark: HTML_NAMESPACE,
    // 'math': HTML_NAMESPACE,
    menu: HTML_NAMESPACE,
    meta: HTML_NAMESPACE,
    meter: HTML_NAMESPACE,
    nav: HTML_NAMESPACE,
    noscript: HTML_NAMESPACE,
    object: HTML_NAMESPACE,
    ol: HTML_NAMESPACE,
    optgroup: HTML_NAMESPACE,
    option: HTML_NAMESPACE,
    output: HTML_NAMESPACE,
    p: HTML_NAMESPACE,
    picture: HTML_NAMESPACE,
    pre: HTML_NAMESPACE,
    progress: HTML_NAMESPACE,
    q: HTML_NAMESPACE,
    rp: HTML_NAMESPACE,
    rt: HTML_NAMESPACE,
    ruby: HTML_NAMESPACE,
    s: HTML_NAMESPACE,
    samp: HTML_NAMESPACE,
    script: HTML_NAMESPACE,
    section: HTML_NAMESPACE,
    select: HTML_NAMESPACE,
    slot: HTML_NAMESPACE,
    small: HTML_NAMESPACE,
    source: HTML_NAMESPACE,
    span: HTML_NAMESPACE,
    strong: HTML_NAMESPACE,
    style: HTML_NAMESPACE,
    sub: HTML_NAMESPACE,
    summary: HTML_NAMESPACE,
    sup: HTML_NAMESPACE,
    // 'svg': HTML_NAMESPACE,
    table: HTML_NAMESPACE,
    tbody: HTML_NAMESPACE,
    td: HTML_NAMESPACE,
    template: HTML_NAMESPACE,
    textarea: HTML_NAMESPACE,
    tfoot: HTML_NAMESPACE,
    th: HTML_NAMESPACE,
    thead: HTML_NAMESPACE,
    time: HTML_NAMESPACE,
    title: HTML_NAMESPACE,
    tr: HTML_NAMESPACE,
    track: HTML_NAMESPACE,
    u: HTML_NAMESPACE,
    ul: HTML_NAMESPACE,
    var: HTML_NAMESPACE,
    video: HTML_NAMESPACE,
    wbr: HTML_NAMESPACE,

    // SVG Elements per https://developer.mozilla.org/en-US/docs/Web/SVG/Element
    //'a': SVG_NAMESPACE,
    animate: SVG_NAMESPACE,
    animateMotion: SVG_NAMESPACE,
    animateTransform: SVG_NAMESPACE,
    circle: SVG_NAMESPACE,
    clipPath: SVG_NAMESPACE,
    defs: SVG_NAMESPACE,
    desc: SVG_NAMESPACE,
    discard: SVG_NAMESPACE,
    ellipse: SVG_NAMESPACE,
    feBlend: SVG_NAMESPACE,
    feColorMatrix: SVG_NAMESPACE,
    feComponentTransfer: SVG_NAMESPACE,
    feComposite: SVG_NAMESPACE,
    feConvolveMatrix: SVG_NAMESPACE,
    feDiffuseLighting: SVG_NAMESPACE,
    feDisplacementMap: SVG_NAMESPACE,
    feDistantLight: SVG_NAMESPACE,
    feDropShadow: SVG_NAMESPACE,
    feFlood: SVG_NAMESPACE,
    feFuncA: SVG_NAMESPACE,
    feFuncB: SVG_NAMESPACE,
    feFuncG: SVG_NAMESPACE,
    feFuncR: SVG_NAMESPACE,
    feGaussianBlur: SVG_NAMESPACE,
    feImage: SVG_NAMESPACE,
    feMerge: SVG_NAMESPACE,
    feMergeNode: SVG_NAMESPACE,
    feMorphology: SVG_NAMESPACE,
    feOffset: SVG_NAMESPACE,
    fePointLight: SVG_NAMESPACE,
    feSpecularLighting: SVG_NAMESPACE,
    feSpotLight: SVG_NAMESPACE,
    feTile: SVG_NAMESPACE,
    feTurbulence: SVG_NAMESPACE,
    filter: SVG_NAMESPACE,
    foreignObject: SVG_NAMESPACE,
    g: SVG_NAMESPACE,
    hatch: SVG_NAMESPACE,
    hatchpath: SVG_NAMESPACE,
    image: SVG_NAMESPACE,
    line: SVG_NAMESPACE,
    linearGradient: SVG_NAMESPACE,
    marker: SVG_NAMESPACE,
    mask: SVG_NAMESPACE,
    metadata: SVG_NAMESPACE,
    mpath: SVG_NAMESPACE,
    path: SVG_NAMESPACE,
    pattern: SVG_NAMESPACE,
    polygon: SVG_NAMESPACE,
    polyline: SVG_NAMESPACE,
    radialGradient: SVG_NAMESPACE,
    rect: SVG_NAMESPACE,
    //'script': SVG_NAMESPACE,
    set: SVG_NAMESPACE,
    stop: SVG_NAMESPACE,
    //'style': SVG_NAMESPACE,
    svg: SVG_NAMESPACE,
    switch: SVG_NAMESPACE,
    symbol: SVG_NAMESPACE,
    text: SVG_NAMESPACE,
    textPath: SVG_NAMESPACE,
    //'title': SVG_NAMESPACE,
    tspan: SVG_NAMESPACE,
    use: SVG_NAMESPACE,
    view: SVG_NAMESPACE,

    // MATHML Elements per https://developer.mozilla.org/en-US/docs/Web/MathML/Element
    math: MATHML_NAMESPACE,
    maction: MATHML_NAMESPACE,
    annotation: MATHML_NAMESPACE,
    'annotation-xml': MATHML_NAMESPACE,
    menclose: MATHML_NAMESPACE,
    merror: MATHML_NAMESPACE,
    mfenced: MATHML_NAMESPACE,
    mfrac: MATHML_NAMESPACE,
    mi: MATHML_NAMESPACE,
    mmultiscripts: MATHML_NAMESPACE,
    mn: MATHML_NAMESPACE,
    none: MATHML_NAMESPACE,
    mo: MATHML_NAMESPACE,
    mover: MATHML_NAMESPACE,
    mpadded: MATHML_NAMESPACE,
    mphantom: MATHML_NAMESPACE,
    mprescripts: MATHML_NAMESPACE,
    mroot: MATHML_NAMESPACE,
    mrow: MATHML_NAMESPACE,
    ms: MATHML_NAMESPACE,
    semantics: MATHML_NAMESPACE,
    mspace: MATHML_NAMESPACE,
    msqrt: MATHML_NAMESPACE,
    mstyle: MATHML_NAMESPACE,
    msub: MATHML_NAMESPACE,
    msup: MATHML_NAMESPACE,
    msubsup: MATHML_NAMESPACE,
    mtable: MATHML_NAMESPACE,
    mtd: MATHML_NAMESPACE,
    mtext: MATHML_NAMESPACE,
    mtr: MATHML_NAMESPACE,
    munder: MATHML_NAMESPACE,
    munderover: MATHML_NAMESPACE,
};

export const elementNamespaceTransitionMap: Record<
    string,
    Record<string, { node: string; children: string } | undefined> | undefined
> = {
    [HTML_NAMESPACE]: {
        svg: {
            node: SVG_NAMESPACE,
            children: SVG_NAMESPACE,
        },
        math: {
            node: MATHML_NAMESPACE,
            children: MATHML_NAMESPACE,
        },
    },
    [SVG_NAMESPACE]: {
        foreignObject: {
            node: SVG_NAMESPACE,
            children: HTML_NAMESPACE,
        },
    },
} as const;
